defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: [H.A. Mohtashami]
subtitle: [Researcher & Lecturer]
description: [Ferdowsi University of Mashhad]

# Side Menu Links
menu:
  - text: Home
    link: /
    icon: ""

  - text: Research
    link: /skills-and-offers
    icon: ""

  - text: Teaching
    link: /contact
    icon: ""

  - text: Software
    link: /resume
    icon: ""

# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/hamb8066
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/hamb8066
    icon: fab fa-github-square

  - name: facebook
    link: https://www.facebook.com/hamb8066
    icon: fab fa-facebook-square

  - name: twitter
    link: https://www.twitter.com/hamb8066
    icon: fab fa-twitter


    
